// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDCtAqaCWgt27INIeyGBYtaxueg5RbYA',
    appId: '1:678381142054:web:d0833bffa7e215442666e7',
    messagingSenderId: '678381142054',
    projectId: 'fp-indonesaku',
    authDomain: 'fp-indonesaku.firebaseapp.com',
    storageBucket: 'fp-indonesaku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTCn7GMk5T1Ohxky80u6kJ7utQu16MqWk',
    appId: '1:678381142054:android:556e0bea22fba0c12666e7',
    messagingSenderId: '678381142054',
    projectId: 'fp-indonesaku',
    storageBucket: 'fp-indonesaku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWAWoyQKuOmLwWh4K_03iju7nlCt4psaU',
    appId: '1:678381142054:ios:86947cd5380802b42666e7',
    messagingSenderId: '678381142054',
    projectId: 'fp-indonesaku',
    storageBucket: 'fp-indonesaku.firebasestorage.app',
    iosBundleId: 'com.example.indonesaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWAWoyQKuOmLwWh4K_03iju7nlCt4psaU',
    appId: '1:678381142054:ios:86947cd5380802b42666e7',
    messagingSenderId: '678381142054',
    projectId: 'fp-indonesaku',
    storageBucket: 'fp-indonesaku.firebasestorage.app',
    iosBundleId: 'com.example.indonesaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDCtAqaCWgt27INIeyGBYtaxueg5RbYA',
    appId: '1:678381142054:web:fbe2d4b3ccf5a6d42666e7',
    messagingSenderId: '678381142054',
    projectId: 'fp-indonesaku',
    authDomain: 'fp-indonesaku.firebaseapp.com',
    storageBucket: 'fp-indonesaku.firebasestorage.app',
  );
}
