import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/homepage_screen.dart';

// Replace this with your actual firebase_options.dart generated by FlutterFire CLI
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform, // uncomment when firebase_options.dart is ready
  );
  runApp(const IndoneSakuApp());
}

class IndoneSakuApp extends StatelessWidget {
  const IndoneSakuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IndoneSaku',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFB5451B),
          brightness: Brightness.light,
        ),
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: const Color(0xFFF7F3EE),
      ),
      home: const HomepageScreen(),
    );
  }
}
